# Pull docker registry pull secret from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-pull-secret-es
  namespace: cert-manager
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    creationPolicy: Owner
    name: registry-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .secret | b64dec | toString }}"
      engineVersion: v2
  data:
    - secretKey: secret
      remoteRef:
        key: secret/data/registry/pull-secret
        property: dockerconfigjson