KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_connect-worker="connect-secret"
  user_kafka-ui="kafka-ui-secret"
  user_orders-producer="orders-prod-secret"
  user_payments-consumer="payments-cons-secret"
  user_schema-registry="schema-registry-secret";
};