apiVersion: v1
kind: ConfigMap
metadata:
  name: reloader-values
  namespace: reloader
data:
  values.yaml: |
    reloader:
      deployment:
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
          requests:
            cpu: "10m"
            memory: "128Mi"